name: Deploy to AzureWebapp
on:
  push:
    branches:
      - master
      - develop
    workflow_dispatch:
    
jobs:
  build-application:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: ls
        run: ls


