name: Deploy to AzureWebapp
on:
  push:
    branches:
      - master
      - develop
    workflow_dispatch:
    
jobs:
  build-application:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
      - uses: actions/checkout@v3

      - name: buil applicaiton
        run: dotnet publish -c Release -o ./gh-action
      
      - name: upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .web-app
          path: ./gh-action





