name: Merge Validation test
on: 
  - push
  - pull_request
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: run test
        run: |
          EXIT_CODE=1
          exit $EXIT_CODE 